### ISSUE TITLE
line-dasharray cartocss attribute not working

### ISSUE THREAD

**Issue by javisantana** [CartoDB/d3.cartodb#116]
- render a polygon layer with

``` css
 #test { 
   line-color: #ccc;
   line-dasharray: 4;
 }
```

should render dashed lines
