### ISSUE TITLE
Map {} cartocss fails in styleForSymbolizer

### ISSUE THREAD

**Issue by rochoa** [CartoDB/d3.cartodb#178]
When using a CartoCSS with `Map` to, for instance, modify the buffer-size the `styleForSymbolizer` fails because style is invalid on later usages:

![screen shot 2016-04-28 at 16 41 42](https://cloud.githubusercontent.com/assets/45346/14889771/68887c24-0d60-11e6-8646-9ca6de4e2b7d.png)

It raises a `Uncaught TypeError: Cannot read property 'radius' of undefined`.

CartoCSS example:

``` css
Map {
  buffer-size: 32;
}

#populated_places_simple_reduced{
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 1;
  marker-line-opacity: 1;
  marker-placement: point;
  marker-type: ellipse;
  marker-width: 96;
  marker-fill: #081B47;
  marker-allow-overlap: true;
}
```
